name: FactionsHCF
author: BajanVlogs
description: A Advanced HCF Plugin Made In 1 Day
version: 1.3.10-dev1
main: FactionsHCF\FactionMain
api: [3.0.0-ALPHA5, 3.0.0-ALPHA6]
commands:
  f:
    description: use /f help for all parameters
    permission: f.command
permissions:
  f.command:
    default: true
    description: "Allow use of all faction commands"